name: Build EBOOTs and Publish Release
on: [push]
jobs:
  Compile-EBOOTs:
    runs-on: ubuntu-latest
    container:
      image: bmaupin/pspdev
    steps:
      - uses: actions/checkout@v2
      - name: Get apt ready
        run: |
          apt update
          apt install -y zip
      - name: Build
        working-directory: ./
        run: |
          cd source/libpspmath
          make && make install
          cd ../../
          make -f MakePHAT install
          make -f MakePHAT clean
          make -f MakeSLIM install
      - name: Generate Build Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M-%S')"
      - name: Zip EBOOTs
        working-directory: ./build
        run: |
          zip -r psp-nzp-eboots.zip EBOOT.PBP EBOOT2000.PBP
      - name: Delete Old Release
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: bleeding-edge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: bleeding-edge
          release_name: Automated Release ${{ steps.date.outputs.date }}
          body: |
            This is a **bleeding edge** NZ:P PSP EBOOT release, stability is not guarenteed.

            To install:
            - Grab the .ZIP archive (psp-nzp-eboots.zip)
            - Extract the contents of the .ZIP archive to `PSP/GAME/nzportable`.
            - If on PSP SLIM, delete `EBOOT.PBP` and rename `EBOOT2000.PBP` to `EBOOT.PBP`.
          draft: true
          prerelease: false
      - name: Upload EBOOT Archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/psp-nzp-eboots.zip
          asset_name: psp-nzp-eboots.zip
          asset_content_type: application/zip
      - name: Publish Release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}

